### ISSUE TITLE
Do we need some kind of Discord channel to discuss stuff about this library?

### ISSUE THREAD

**Issue by Alexei-Kornienko** [zeromq/zmq.rs#114]

**Comment by TheButlah** [comment]
I wouldn't complain about a discord channel. There is also the new github discussions tab. I have never used that however.

**Comment by TheButlah** [comment]
Looking into github discussions, I it looks like its better suited to asking and answering questions about the usage of the library. I'd be down for a discord. Email me with the link

**Comment by TheButlah** [comment]
Actually I guess the discord should be public, so no reason not to just paste the link here

**Comment by Alexei-Kornienko** [comment]
Yeah. I think we can just add it to README.. just need to select a server for this

**Comment by TheButlah** [comment]
I'm on East coast USA, if that helps

**Comment by Alexei-Kornienko** [comment]
https://discord.gg/G8jEhXQa

**Comment by JonnyOThan** [comment]
this invite link is no longer valid

**Comment by Alexei-Kornienko** [comment]
Generated a permanent link - https://discord.gg/pFXSqWtjQT
