### ISSUE TITLE
Directions using `async-std`

### ISSUE THREAD

**Issue by xpepermint** [zeromq/zmq.rs#128]
I tried to use this crate with `async-std` but whatever I do it requires `tokio` and I get a bunch of errors. There's a helper in the examples folder that should enable both runtimes but it doesn't work for me. 

Could you please add notes to the README on how to use this library with `tokio` and `async-std`. Thanks.

**Comment by Alexei-Kornienko** [comment]
@TheButlah Could I ask you to add missing details in README? I'm pretty sure that you can do it better than I would.

**Comment by TheButlah** [comment]
@xpepermint I've submitted a PR to improve the usage documentation. Does that answer your question?

**Comment by xpepermint** [comment]
Thanks, @TheButlah for your quick response. I believe you answered it because I realized I forgot to add `default-features = false`. A lack of sleep I guess - the documentation will now prevent such things :).
