### ISSUE TITLE
Unrecognized feature flags in published crate

### ISSUE THREAD

**Issue by clegaard** [zeromq/zmq.rs#141]
When using the 0.2.0 crate published to crates.io, it seems using the non-default feature flags is causing issues.

Defining the dependency as:
``` toml
zeromq = { version = "0.2.0", default-features = false, features = [
    "tokio-runtime",
    "tcp-transport",
] }
```
results in the following error
```
error: failed to select a version for `zeromq`.
    ... required by package `fmi2api v0.1.0 (/home/clegaard/Desktop/repos/unifmu/fmi2api)`
versions that meet the requirements `^0.2.0` are: 0.2.0

the package `fmi2api` depends on `zeromq`, with features: `tcp-transport` but `zeromq` does not have these features.
```
Specifying the Git repo as the source of the dependency appears to solve the issue:
``` toml 
zeromq = { git = "https://github.com/zeromq/zmq.rs.git", default-features = false, features = [
    "tokio-runtime",
    "tcp-transport",
] }
```
By the way great work on the library, I hope to see it evolve even further in the future :)

**Comment by Alexei-Kornienko** [comment]
Yeah it seems that I just need to publish a version 0.2.1 to crates.io I'll do it in a few days

**Comment by Alexei-Kornienko** [comment]
Should be fixed now. I've uploaded a recent version to crates.io
