### ISSUE TITLE
Use async mutexes

### ISSUE THREAD

**Issue by andrewwhitehead** [zeromq/zmq.rs#161]
Or mutices?

It's not safe to use the parking_lot or std::sync Mutex within async tasks, as the mutex may be locked by another task on the same thread as one attempting to obtain the lock, leading to a deadlock. It also blocks the current executor thread while awaiting the mutex, preventing other tasks from executing.

The [`async-lock`](https://docs.rs/async-mutex/latest/async_lock/) crate is a good option, except that `FairQueue` looks like it will need significant modifications.

**Comment by Alexei-Kornienko** [comment]
I'm not sure that this is an actual problem. Could you please point out exact place in the code where it can cause troubles?
Async code is not switching tasks in random places. Every yield is explicit and compiler is tracking that mutex is not held across yield point.

**Comment by andrewwhitehead** [comment]
Indeed it looks like the deadlocking issue won't happen in practice as the MutexGuard is not Send, and the containing Futures are required to be. I'm still a little concerned about the potential for blocking an executor thread while awaiting the mutex but any changes there are likely just a performance optimization, and the async mutex is inherently a little more expensive than a standard one. Tokio has some relevant advice on when to use an async mutex which seems to agree with the current usage: https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use

**Comment by Alexei-Kornienko** [comment]
>I'm still a little concerned about the potential for blocking an executor thread while awaiting the mutex but any changes there are likely just a performance optimization

In the case when we *need* a mutex we still *need* to lock *some* thread on it. There is no easy way of not locking an executor thread cause it means that some other thread will be locked anyway

**Comment by andrewwhitehead** [comment]
With an async mutex the task yields back to the executor instead of blocking the whole thread, allowing other tasks on the same thread to (potentially) run.
