### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by mxplusb** [zeromq/zmq.rs#181]
Hi, love this port of the C++ code!

Looking at the disclaimer, it sounds like there's quite a bit left to go to get things close to the specification. I'm evaluating a rewrite of one of my projects into Rust, but that means I lose embedded NATS. I'm considering ZeroMQ, and this port is of particular interest because it's native Rust, so no C/C++ bindings. I'd be interested in contributing to this port to bring it up to spec, but I would want to implement a QUIC-based socket provider as part of the contribution.

Is there interest in further contributions, and what is the current status of this port?

**Comment by jonasbostoen** [comment]
Interested in this as well

**Comment by poyea** [comment]
This is still maintained; however the release is limited for now. If you've got any change requiring reviews, feel free to ping me. Of course releases will be made when needed. Priority is still the issues we raised already and incremental changes are definitely welcomed.

**Comment by mmastrac** [comment]
@poyea We started using this in Deno for our Jupyter support -- would it be possible to merge some of the modernization/dependency optimization PRs in #178, #179 and #180 and push a new release?

Happy to help if needed.

Thanks!

**Comment by mmastrac** [comment]
Quick ping on this -- happy to help, and if needed be a temporary maintainer to assist with landing some of the patches.

**Comment by rgbkrk** [comment]
@mmastrac I'll get you added in so you can help with maintenance.

**Comment by rgbkrk** [comment]
Closing as the project has new life and a new release. @mxplusb please open a new issue for QUIC. You may want to weigh in on the QUIC issue in libzmq: https://github.com/zeromq/libzmq/issues/3988
