### ISSUE TITLE
Please provide status of rewrite

### ISSUE THREAD

**Issue by vladimir-lu** [zeromq/zmq.rs#38]
I would be interested in helping this but need to know current status.

**Comment by fantix** [comment]
@vladimir-lu Sorry for the late reply! All progress is on master, I suppose it will require quite some effort to get things up to date. Unfortunately I'm still occupied by different distractions, so please try anything as will :)

**Comment by noxecane** [comment]
What exactly is the rewrite about so one might help

**Comment by fantix** [comment]
I would expect it to be a new implementation from scratch of [ZMTP](https://rfc.zeromq.org/spec:23/ZMTP/) and ZeroMQ APIs, based on a concurrency framework.

**Comment by tmccombs** [comment]
It would probably make sense to use Tokio.

**Comment by fantix** [comment]
Exactly - there was no Tokio when this project was created, so it would probably be a rewritten of this rewritten.

**Comment by soloradish** [comment]
Any update?

**Comment by Alexei-Kornienko** [comment]
I'm working on native impl as my pet project - https://github.com/Alexei-Kornienko/zmq-rs
Right now it's an early WIP however if someone would be interested in it maybe it could become something bigger than just a pet project

**Comment by Alexei-Kornienko** [comment]
Published a newer version 0.2.0 on crates.io. Would appreciate any kind of feedback.
