### ISSUE TITLE
looking to contribute

### ISSUE THREAD

**Issue by TheButlah** [zeromq/zmq.rs#58]
Hi, I use zmq and would love a native rust version. I'm looking to help out and contribute. Are there any features to implement that are low hanging fruit and simple for a beginning/intermediate rust developer to work on? Any particular parts of the codebase you suggest I look at to become familiar with?

Are there any project boards or other feature-tracking systems being used so contributors might now what they can help with? Or is the best way to just look at the github issues?

**Comment by Alexei-Kornienko** [comment]
Right now I'm working on implementing different socket types. For example you can check recent changes to req/rep sockets and see implemenation of Dealer/Router sockets. Currently https://github.com/zeromq/zmq.rs/blob/master/src/dealer_router.rs#L108 works but it's not fully compliant to zeromq specification (fair queuing) and it needs refactoring. You can start with looking on it's code and try to refactor to use the same approach as currently used in Rep socket in terms of fair queue
