### ISSUE TITLE
What is SocketBackend and PubSocketBackend?

### ISSUE THREAD

**Issue by TheButlah** [zeromq/zmq.rs#69]
What is the purpose of `SocketBackend`, and what do you mean by "backend" in this context? Also, when should a method be in `Socket` vs `SocketBackend`, and what is the purpose of having both `PubSocket` and `PubSocketBackend`?

Is there a general rule of thumb or explanation on the concepts at play here to help people contribute more easily?

**Comment by Alexei-Kornienko** [comment]
Socket (and PubSocket for example) is a structure that is owned by user. This is a frontend part that can be used directly to send and receive messages. It has some basic methods like `send`/`recv` and it could also have some specialized methods (for example `subscribe` for SubSocket). So when this structure is dropped all resources associated with this socket should be freed

However internals are much more complicated then just a single structure. For example when you open a port to accept new connections you need a background coroutine that handles logic of accepting connections and doing handshake. So in general SocketBackend is a structure that is shared between the user owned Socket and all the internal parts that are needed to send/recv messages. PubSocketBackend and other concrete backends implement logic that is specific for each socket type. For example see spec - https://rfc.zeromq.org/spec/29/ "SHALL maintain a single outgoing message queue for each connected subscriber." PUB socket doesn't have a queue for incoming messages however SUB sockets can send messages to it that control subscription setting and it's handled transparently for end user.

I'm not sure that this is the optimal way of doing stuff. I'm still trying to find a best solution in terms of not duplicating the same code between different sockets vs implementing custom socket behaviour.
