### ISSUE TITLE
Multiple calls to bind will cause resource leak

### ISSUE THREAD

**Issue by Alexei-Kornienko** [zeromq/zmq.rs#71]
User may call `socket.bind("...")` multiple times. Overall socket should work properly (accepting connections from several endpoints) However only last stop_handle will be used to stop accepting new connections. Handles from previous call will be lost and cause possible issues/resource leak

IMHO we should either prevent user from calling bind multiple times or make sure that we save all stop handles in some vec

**Comment by TheButlah** [comment]
The ZMQ C api lets users bind multiple times, and presumably we should allow users to bind somewhere, and then bind again at some later point in time. Therefore saving the stop handles is probably the right move
