### ISSUE TITLE
Ipc sockets have race conditions when binding to the same path

### ISSUE THREAD

**Issue by TheButlah** [zeromq/zmq.rs#87]
When socket `B` binds to a path used by socket `A`, `B` gets an error. However, if `A` is deleted/unbound and then `B` immediately attempts to bind, the path may not yet have been deleted. In this case, `B` gets an error when the code would imply that the socket path should no longer be used by `A`.

We should probably add some retry logic in the bind method of ipc sockets (or all sockets?) to alleviate this issue, or otherwise we should have an async unbind method that doesn't return until the file is deleted and unbound. I suspect this latter approach is the ideal one

**Comment by TheButlah** [comment]
@Alexei-Kornienko I suspect that the reason this is happening is that when the socket is `drop`ped, the `AcceptStopChannel` gets dropped, which causes the accept loop to break. The cleanup code in the accept task will then run, but nothing prevents the `drop()` method of the socket from blocking until that completes. Instead, we should have an `unbind()` method that sockets can call to unbind. This will be invoked in the `drop()` function.

In order for such an unbind function to work, we need to hold the JoinHandle of the accept task, in addition to the `AcceptStopChannel`. Where should I store this data? I am not sure if it should go in the socket backend or the regular socket struct. I'm still a bit unclear on what the difference between the two is.

**Comment by Alexei-Kornienko** [comment]
We won't be able to call `unbind()` in `drop()` function. unbind would be async and drop must be synchronous. Currently it works in such a way that dropping socket will `eventually` free all allocated resources.

**Comment by TheButlah** [comment]
You're right - I just learned this the hard way after going down the rabbit hole of Async Drop RFCs and other blog posts.

What I'm currently looking at is introducing a general purpose `TaskHandle<T>` struct, that has one method- `async fn shutdown(self) -> ZmqResult<T>`. The task handle will contain both the shutdown channel as well as the JoinHandle from tokio. We can't run `shutdown()` in the destructor (due to the aforementioned issue), but we can hold this handle and call shutdown on it where appropriate in our code where we need to await on the task. In the general case where we instead `Drop` the handle without any explicit async shutdown, we still know that it will eventually shutdown, because the stop channel is cancelled and the task will then leave its `loop`.

This strikes a good balance to me - eventual shutdown as a default, with the ability to await shutdown when needed.

**Comment by TheButlah** [comment]
This is fixed by #89
